enabled: true

jenkins:
  baseUrl: "https://ci.athion.net"
  jobPath: "/job/FastAsyncWorldEdit"
  build: "lastSuccessfulBuild"

artifact:
  prefix: "FastAsyncWorldEdit-Paper"
  suffix: ".jar"

target:
  jarName: "FastAsyncWorldEdit.jar"
  # true - plugins/update/<jarName> (recommended)
  # false - plugins/<jarName>
  useUpdateFolder: true

network:
  connectTimeoutMillis: 10000
  readTimeoutMillis: 30000
  maxRedirects: 5

proxy:
  # Proxy settings for network requests (http)
  enabled: false
  host: "127.0.0.1"
  port: 8000
  username: "abcdef"
  password: "abcdef"
